services:
  pytunnel-server:
    build: .
    container_name: pytunnel-server
    ports:
      - "8765:8765"  # WebSocket port
      - "8081:8081"  # HTTP port
    environment:
      - USE_SSL=true
      - PUBLIC_HOST=your-domain.com  # Change this to your domain
      - AUTH_TOKEN=your-secret-token  # Change this to a secure token
    volumes:
      - ./certs:/app/certs
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy (nginx) for production
  nginx:
    image: nginx:alpine
    container_name: pytunnel-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - pytunnel-server
    restart: unless-stopped
    profiles:
      - production
