services:
  - type: web
    name: pytunnel-server
    env: python
    plan: free
    buildCommand: pip install -r requirements_builtin.txt
    startCommand: python server_builtin.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /health
    autoDeploy: true
    region: oregon
    numInstances: 1
