services:
  - type: web
    name: pytunnel-server
    env: python
    plan: free
    buildCommand: pip install -r requirements_flask_simple.txt
    startCommand: python server_flask_simple.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
    region: oregon
    numInstances: 1
